export const styles = () => ({
    logo: {
        textAlign: "center",
        color: "#ccc",
        fontSize: "18px",
        cursor: "pointer",
        display: "inline-block",
    },
    contentArea: {
        position: "fixed",
        width: "700px",
        height: "500px",
        top: "50%",
        left: "50%",
        marginTop: "-200px",
        marginLeft: "-350px",
    },
    helpText: {
        position: "absolute",
        top: "220px",
        left: "300px",
        width: "400px",
        textAlign: "justify",
        marginLeft: "0px",
        marginTop: "0px",
        fontSize: "15px",
    },
    inputGroupAddon: {
        width: "130px",
        padding: "12px",
        margin: "auto",
    },
    inputGroup: {
        width: "100%",
        marginTop: "10px",
        display: "flex",
    },
    formControl: {
        fontSize: "15px",
        height: "35px",
        width: "250px",
        borderRadius: "6px",
        padding: "3px",
    },
    uploadFile: {
        display: "none",
    },
    uploadLogo: {
        width: "150px",
        height: "50px",
        background: `url("img/upload_b.png")`,
        backgroundSize: "100% 100%",
        zIndex: 100,
        cursor: "pointer",
        marginLeft: "25px",
        marginRight: "25px",
        display: "inline-block",
    },
    downloadLogo: {
        width: "150px",
        height: "50px",
        background: `url("img/download_b.png")`,
        backgroundSize: "100% 100%",
        zIndex: 100,
        cursor: "pointer",
        marginLeft: "20px",
        display: "inline-block",
    },
    mediumFont: {
        fontSize: "18px",
        fontWeight: "bold",
    },
    smallFont: {
        fontSize: "14px",
    },
    actionButtons: {
        position: "absolute",
        top: "130px",
        left: "300px",
        width: "400px",
        height: "50px",
    },
    templateSelect: {
        position: "absolute",
        left: "300px",
        top: 0,
        width: "400px",
        marginLeft: "0px",
        marginTop: "0px",
        fontSize: "15px",
    },
});
